apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-woodpecker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mattjmorrison/homelab-woodpecker
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: woodpecker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
