apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mattjmorrison/homelab-grafana
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
