apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-kube-state-metrics
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mattjmorrison-homelab/homelab-kube-state-metrics
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 30s
