apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-openbao
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://openbao.github.io/openbao-helm
      chart: openbao
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/values.yaml
    - repoURL: https://github.com/mattjmorrison/homelab-openbao
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: openbao
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
