apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-external-secrets
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/values.yaml
    - repoURL: https://github.com/mattjmorrison-homelab/homelab-external-secrets
      targetRevision: HEAD
      path: verify
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 30s
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
