apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-argocd-image-updater
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mattjmorrison-homelab/homelab-argocd-image-updater
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
